# Site settings
title: Palmberry
tagline: blog
email: logle.cn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi,Iâ€™m a IT dog.
  I love my son.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://7throbot.com" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Jinyong Liu"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#7B68EE" #"#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: palmberry
    weibo: Palm_Berry
    # twitter: logle.cn
    # facebook: logle.cn
    # gplus: +logle.cn
    # dribble: logle.cn
    # pinterest: logle.cn

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  Disqus comments manager - shortname
  disqus_shortname: jinyongliu

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-72120350-1
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
